package com.hdsx.lwgl.tjfx.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class MainTainCluster{
    private int id;
    public String getRoadcode() {
        return roadcode;
    }

    public void setRoadcode(String roadcode) {
        this.roadcode = roadcode;
    }

    public String getRoadname() {
        return roadname;
    }

    public void setRoadname(String roadname) {
        this.roadname = roadname;
    }

    public BigDecimal getRoadstart() {
        return roadstart;
    }

    public void setRoadstart(BigDecimal roadstart) {
        this.roadstart = roadstart;
    }

    public BigDecimal getRoadend() {
        return roadend;
    }

    public void setRoadend(BigDecimal roadend) {
        this.roadend = roadend;
    }

    public String getRoadfullname() {
        return roadfullname;
    }

    public void setRoadfullname(String roadfullname) {
        this.roadfullname = roadfullname;
    }

    public String getRoadrang() {
        return roadrang;
    }

    public void setRoadrang(String roadrang) {
        this.roadrang = roadrang;
    }

    public Short getDirection() {
        return direction;
    }

    public void setDirection(Short direction) {
        this.direction = direction;
    }

    public List<T_BLOCK_YH_CURRENT> getData() {
        return data;
    }

    public void setData(List<T_BLOCK_YH_CURRENT> data) {
        this.data = data;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.ROADCODE
     *
     * @mbggenerated
     */

    private String roadcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.ROADNAME
     *
     * @mbggenerated
     */
    private String roadname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.ROADNAME
     *
     * @mbggenerated
     */
    private String roadfullname;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.ROADSTART
     *
     * @mbggenerated
     */
    private BigDecimal roadstart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.ROADEND
     *
     * @mbggenerated
     */
    private BigDecimal roadend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.ROADEND
     *
     * @mbggenerated
     */
    private String roadrang;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.DIRECTION
     *
     * @mbggenerated
     */
    private Short direction;

    public String getDirectiontext() {
        return directiontext;
    }

    public void setDirectiontext(String directiontext) {
        this.directiontext = directiontext;
    }

    private String directiontext;

    private List<T_BLOCK_YH_CURRENT> data;

    //几何属性（WKT）
    private String geometry;

    public String getGeometry() {
        return geometry;
    }

    public void setGeometry(String geometry) {
        this.geometry = geometry;
    }

    public String getGeometryType() {
        return geometryType;
    }

    public void setGeometryType(String geometryType) {
        this.geometryType = geometryType;
    }

    //几何类型
    private String geometryType;

    public Object clone() {
        MainTainCluster o = null;
        o = new MainTainCluster();
        o.setId(this.id);
        o.setRoadcode(this.roadcode);
        o.setRoadname(this.roadname);
        o.setRoadstart(this.roadstart);
        o.setRoadend(this.roadend);
        o.setDirection(this.direction);
        if(this.data!=null){
            List<T_BLOCK_YH_CURRENT> newData = (List<T_BLOCK_YH_CURRENT>)((ArrayList<T_BLOCK_YH_CURRENT>)this.data).clone();
            o.setData(newData);
        }
        return o;
    }
}
