package com.hdsx.lwgl.statanalysis.entity;

import java.math.BigDecimal;
import java.util.Date;

public class T_BLOCK_YH_CURRENT {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.ROADCODE
     *
     * @mbggenerated
     */
    private String roadcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.ROADNAME
     *
     * @mbggenerated
     */
    private String roadname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.SEGMENT_CODE
     *
     * @mbggenerated
     */
    private String segmentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.SEGMENT_NAME
     *
     * @mbggenerated
     */
    private String segmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.BLOCK_REASON
     *
     * @mbggenerated
     */
    private String blockReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.DETECT_TIME
     *
     * @mbggenerated
     */
    private Date detectTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.ESTIMATE_TIME
     *
     * @mbggenerated
     */
    private Date estimateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.RESUME_TIME
     *
     * @mbggenerated
     */
    private Date resumeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.ROADSTART
     *
     * @mbggenerated
     */
    private BigDecimal roadstart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.ROADEND
     *
     * @mbggenerated
     */
    private BigDecimal roadend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.DIRECTION
     *
     * @mbggenerated
     */
    private Short direction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.SCENE_DESC
     *
     * @mbggenerated
     */
    private String sceneDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.REPORT_UNIT
     *
     * @mbggenerated
     */
    private String reportUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.REPORT_USER
     *
     * @mbggenerated
     */
    private String reportUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.REPORT_USER_PHONE
     *
     * @mbggenerated
     */
    private String reportUserPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.DISTCODE
     *
     * @mbggenerated
     */
    private String distcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.BLOCK_MILEAGE
     *
     * @mbggenerated
     */
    private BigDecimal blockMileage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.SUM_WOUNDED
     *
     * @mbggenerated
     */
    private Short sumWounded;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.SUM_DEAD
     *
     * @mbggenerated
     */
    private Short sumDead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.SUM_DESTORY
     *
     * @mbggenerated
     */
    private Short sumDestory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.SUM_DETAIN
     *
     * @mbggenerated
     */
    private Short sumDetain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.CLOSEABLE
     *
     * @mbggenerated
     */
    private Short closeable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.SYS_OTIME
     *
     * @mbggenerated
     */
    private Date sysOtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.SOURCE
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.MEASURES
     *
     * @mbggenerated
     */
    private String measures;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.CENTER_POINT
     *
     * @mbggenerated
     */
    private String centerPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.BLOCK_REASON_ID
     *
     * @mbggenerated
     */
    private String blockReasonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.INTERRUPT
     *
     * @mbggenerated
     */
    private Short interrupt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.HAPPEN_TIME
     *
     * @mbggenerated
     */
    private Date happenTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.THROUGH_EFFECT
     *
     * @mbggenerated
     */
    private Short throughEffect;

    public Short getBlock_type() {
        return block_type;
    }

    public void setBlock_type(Short block_type) {
        this.block_type = block_type;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.BLOCK_TYPE
     *
     * @mbggenerated
     */
    private Short block_type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_CURRENT.ID
     *
     * @return the value of T_BLOCK_CURRENT.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_CURRENT.ID
     *
     * @param id the value for T_BLOCK_CURRENT.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_CURRENT.ROADCODE
     *
     * @return the value of T_BLOCK_CURRENT.ROADCODE
     *
     * @mbggenerated
     */
    public String getRoadcode() {
        return roadcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_CURRENT.ROADCODE
     *
     * @param roadcode the value for T_BLOCK_CURRENT.ROADCODE
     *
     * @mbggenerated
     */
    public void setRoadcode(String roadcode) {
        this.roadcode = roadcode == null ? null : roadcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_CURRENT.ROADNAME
     *
     * @return the value of T_BLOCK_CURRENT.ROADNAME
     *
     * @mbggenerated
     */
    public String getRoadname() {
        return roadname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_CURRENT.ROADNAME
     *
     * @param roadname the value for T_BLOCK_CURRENT.ROADNAME
     *
     * @mbggenerated
     */
    public void setRoadname(String roadname) {
        this.roadname = roadname == null ? null : roadname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_CURRENT.SEGMENT_CODE
     *
     * @return the value of T_BLOCK_CURRENT.SEGMENT_CODE
     *
     * @mbggenerated
     */
    public String getSegmentCode() {
        return segmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_CURRENT.SEGMENT_CODE
     *
     * @param segmentCode the value for T_BLOCK_CURRENT.SEGMENT_CODE
     *
     * @mbggenerated
     */
    public void setSegmentCode(String segmentCode) {
        this.segmentCode = segmentCode == null ? null : segmentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_CURRENT.SEGMENT_NAME
     *
     * @return the value of T_BLOCK_CURRENT.SEGMENT_NAME
     *
     * @mbggenerated
     */
    public String getSegmentName() {
        return segmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_CURRENT.SEGMENT_NAME
     *
     * @param segmentName the value for T_BLOCK_CURRENT.SEGMENT_NAME
     *
     * @mbggenerated
     */
    public void setSegmentName(String segmentName) {
        this.segmentName = segmentName == null ? null : segmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_CURRENT.BLOCK_REASON
     *
     * @return the value of T_BLOCK_CURRENT.BLOCK_REASON
     *
     * @mbggenerated
     */
    public String getBlockReason() {
        return blockReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_CURRENT.BLOCK_REASON
     *
     * @param blockReason the value for T_BLOCK_CURRENT.BLOCK_REASON
     *
     * @mbggenerated
     */
    public void setBlockReason(String blockReason) {
        this.blockReason = blockReason == null ? null : blockReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_CURRENT.DETECT_TIME
     *
     * @return the value of T_BLOCK_CURRENT.DETECT_TIME
     *
     * @mbggenerated
     */
    public Date getDetectTime() {
        return detectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_CURRENT.DETECT_TIME
     *
     * @param detectTime the value for T_BLOCK_CURRENT.DETECT_TIME
     *
     * @mbggenerated
     */
    public void setDetectTime(Date detectTime) {
        this.detectTime = detectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_CURRENT.ESTIMATE_TIME
     *
     * @return the value of T_BLOCK_CURRENT.ESTIMATE_TIME
     *
     * @mbggenerated
     */
    public Date getEstimateTime() {
        return estimateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_CURRENT.ESTIMATE_TIME
     *
     * @param estimateTime the value for T_BLOCK_CURRENT.ESTIMATE_TIME
     *
     * @mbggenerated
     */
    public void setEstimateTime(Date estimateTime) {
        this.estimateTime = estimateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_CURRENT.RESUME_TIME
     *
     * @return the value of T_BLOCK_CURRENT.RESUME_TIME
     *
     * @mbggenerated
     */
    public Date getResumeTime() {
        return resumeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_CURRENT.RESUME_TIME
     *
     * @param resumeTime the value for T_BLOCK_CURRENT.RESUME_TIME
     *
     * @mbggenerated
     */
    public void setResumeTime(Date resumeTime) {
        this.resumeTime = resumeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_CURRENT.ROADSTART
     *
     * @return the value of T_BLOCK_CURRENT.ROADSTART
     *
     * @mbggenerated
     */
    public BigDecimal getRoadstart() {
        return roadstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_CURRENT.ROADSTART
     *
     * @param roadstart the value for T_BLOCK_CURRENT.ROADSTART
     *
     * @mbggenerated
     */
    public void setRoadstart(BigDecimal roadstart) {
        this.roadstart = roadstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_CURRENT.ROADEND
     *
     * @return the value of T_BLOCK_CURRENT.ROADEND
     *
     * @mbggenerated
     */
    public BigDecimal getRoadend() {
        return roadend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_CURRENT.ROADEND
     *
     * @param roadend the value for T_BLOCK_CURRENT.ROADEND
     *
     * @mbggenerated
     */
    public void setRoadend(BigDecimal roadend) {
        this.roadend = roadend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_CURRENT.DIRECTION
     *
     * @return the value of T_BLOCK_CURRENT.DIRECTION
     *
     * @mbggenerated
     */
    public Short getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_CURRENT.DIRECTION
     *
     * @param direction the value for T_BLOCK_CURRENT.DIRECTION
     *
     * @mbggenerated
     */
    public void setDirection(Short direction) {
        this.direction = direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_CURRENT.SCENE_DESC
     *
     * @return the value of T_BLOCK_CURRENT.SCENE_DESC
     *
     * @mbggenerated
     */
    public String getSceneDesc() {
        return sceneDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_CURRENT.SCENE_DESC
     *
     * @param sceneDesc the value for T_BLOCK_CURRENT.SCENE_DESC
     *
     * @mbggenerated
     */
    public void setSceneDesc(String sceneDesc) {
        this.sceneDesc = sceneDesc == null ? null : sceneDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_CURRENT.REPORT_UNIT
     *
     * @return the value of T_BLOCK_CURRENT.REPORT_UNIT
     *
     * @mbggenerated
     */
    public String getReportUnit() {
        return reportUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_CURRENT.REPORT_UNIT
     *
     * @param reportUnit the value for T_BLOCK_CURRENT.REPORT_UNIT
     *
     * @mbggenerated
     */
    public void setReportUnit(String reportUnit) {
        this.reportUnit = reportUnit == null ? null : reportUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_CURRENT.REPORT_USER
     *
     * @return the value of T_BLOCK_CURRENT.REPORT_USER
     *
     * @mbggenerated
     */
    public String getReportUser() {
        return reportUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_CURRENT.REPORT_USER
     *
     * @param reportUser the value for T_BLOCK_CURRENT.REPORT_USER
     *
     * @mbggenerated
     */
    public void setReportUser(String reportUser) {
        this.reportUser = reportUser == null ? null : reportUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_CURRENT.REPORT_USER_PHONE
     *
     * @return the value of T_BLOCK_CURRENT.REPORT_USER_PHONE
     *
     * @mbggenerated
     */
    public String getReportUserPhone() {
        return reportUserPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_CURRENT.REPORT_USER_PHONE
     *
     * @param reportUserPhone the value for T_BLOCK_CURRENT.REPORT_USER_PHONE
     *
     * @mbggenerated
     */
    public void setReportUserPhone(String reportUserPhone) {
        this.reportUserPhone = reportUserPhone == null ? null : reportUserPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_CURRENT.DISTCODE
     *
     * @return the value of T_BLOCK_CURRENT.DISTCODE
     *
     * @mbggenerated
     */
    public String getDistcode() {
        return distcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_CURRENT.DISTCODE
     *
     * @param distcode the value for T_BLOCK_CURRENT.DISTCODE
     *
     * @mbggenerated
     */
    public void setDistcode(String distcode) {
        this.distcode = distcode == null ? null : distcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_CURRENT.BLOCK_MILEAGE
     *
     * @return the value of T_BLOCK_CURRENT.BLOCK_MILEAGE
     *
     * @mbggenerated
     */
    public BigDecimal getBlockMileage() {
        return blockMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_CURRENT.BLOCK_MILEAGE
     *
     * @param blockMileage the value for T_BLOCK_CURRENT.BLOCK_MILEAGE
     *
     * @mbggenerated
     */
    public void setBlockMileage(BigDecimal blockMileage) {
        this.blockMileage = blockMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_CURRENT.SUM_WOUNDED
     *
     * @return the value of T_BLOCK_CURRENT.SUM_WOUNDED
     *
     * @mbggenerated
     */
    public Short getSumWounded() {
        return sumWounded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_CURRENT.SUM_WOUNDED
     *
     * @param sumWounded the value for T_BLOCK_CURRENT.SUM_WOUNDED
     *
     * @mbggenerated
     */
    public void setSumWounded(Short sumWounded) {
        this.sumWounded = sumWounded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_CURRENT.SUM_DEAD
     *
     * @return the value of T_BLOCK_CURRENT.SUM_DEAD
     *
     * @mbggenerated
     */
    public Short getSumDead() {
        return sumDead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_CURRENT.SUM_DEAD
     *
     * @param sumDead the value for T_BLOCK_CURRENT.SUM_DEAD
     *
     * @mbggenerated
     */
    public void setSumDead(Short sumDead) {
        this.sumDead = sumDead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_CURRENT.SUM_DESTORY
     *
     * @return the value of T_BLOCK_CURRENT.SUM_DESTORY
     *
     * @mbggenerated
     */
    public Short getSumDestory() {
        return sumDestory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_CURRENT.SUM_DESTORY
     *
     * @param sumDestory the value for T_BLOCK_CURRENT.SUM_DESTORY
     *
     * @mbggenerated
     */
    public void setSumDestory(Short sumDestory) {
        this.sumDestory = sumDestory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_CURRENT.SUM_DETAIN
     *
     * @return the value of T_BLOCK_CURRENT.SUM_DETAIN
     *
     * @mbggenerated
     */
    public Short getSumDetain() {
        return sumDetain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_CURRENT.SUM_DETAIN
     *
     * @param sumDetain the value for T_BLOCK_CURRENT.SUM_DETAIN
     *
     * @mbggenerated
     */
    public void setSumDetain(Short sumDetain) {
        this.sumDetain = sumDetain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_CURRENT.CLOSEABLE
     *
     * @return the value of T_BLOCK_CURRENT.CLOSEABLE
     *
     * @mbggenerated
     */
    public Short getCloseable() {
        return closeable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_CURRENT.CLOSEABLE
     *
     * @param closeable the value for T_BLOCK_CURRENT.CLOSEABLE
     *
     * @mbggenerated
     */
    public void setCloseable(Short closeable) {
        this.closeable = closeable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_CURRENT.SYS_OTIME
     *
     * @return the value of T_BLOCK_CURRENT.SYS_OTIME
     *
     * @mbggenerated
     */
    public Date getSysOtime() {
        return sysOtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_CURRENT.SYS_OTIME
     *
     * @param sysOtime the value for T_BLOCK_CURRENT.SYS_OTIME
     *
     * @mbggenerated
     */
    public void setSysOtime(Date sysOtime) {
        this.sysOtime = sysOtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_CURRENT.SOURCE
     *
     * @return the value of T_BLOCK_CURRENT.SOURCE
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_CURRENT.SOURCE
     *
     * @param source the value for T_BLOCK_CURRENT.SOURCE
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_CURRENT.MEASURES
     *
     * @return the value of T_BLOCK_CURRENT.MEASURES
     *
     * @mbggenerated
     */
    public String getMeasures() {
        return measures;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_CURRENT.MEASURES
     *
     * @param measures the value for T_BLOCK_CURRENT.MEASURES
     *
     * @mbggenerated
     */
    public void setMeasures(String measures) {
        this.measures = measures == null ? null : measures.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_CURRENT.CENTER_POINT
     *
     * @return the value of T_BLOCK_CURRENT.CENTER_POINT
     *
     * @mbggenerated
     */
    public String getCenterPoint() {
        return centerPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_CURRENT.CENTER_POINT
     *
     * @param centerPoint the value for T_BLOCK_CURRENT.CENTER_POINT
     *
     * @mbggenerated
     */
    public void setCenterPoint(String centerPoint) {
        this.centerPoint = centerPoint == null ? null : centerPoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_CURRENT.BLOCK_REASON_ID
     *
     * @return the value of T_BLOCK_CURRENT.BLOCK_REASON_ID
     *
     * @mbggenerated
     */
    public String getBlockReasonId() {
        return blockReasonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_CURRENT.BLOCK_REASON_ID
     *
     * @param blockReasonId the value for T_BLOCK_CURRENT.BLOCK_REASON_ID
     *
     * @mbggenerated
     */
    public void setBlockReasonId(String blockReasonId) {
        this.blockReasonId = blockReasonId == null ? null : blockReasonId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_CURRENT.INTERRUPT
     *
     * @return the value of T_BLOCK_CURRENT.INTERRUPT
     *
     * @mbggenerated
     */
    public Short getInterrupt() {
        return interrupt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_CURRENT.INTERRUPT
     *
     * @param interrupt the value for T_BLOCK_CURRENT.INTERRUPT
     *
     * @mbggenerated
     */
    public void setInterrupt(Short interrupt) {
        this.interrupt = interrupt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_CURRENT.HAPPEN_TIME
     *
     * @return the value of T_BLOCK_CURRENT.HAPPEN_TIME
     *
     * @mbggenerated
     */
    public Date getHappenTime() {
        return happenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_CURRENT.HAPPEN_TIME
     *
     * @param happenTime the value for T_BLOCK_CURRENT.HAPPEN_TIME
     *
     * @mbggenerated
     */
    public void setHappenTime(Date happenTime) {
        this.happenTime = happenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BLOCK_CURRENT.THROUGH_EFFECT
     *
     * @return the value of T_BLOCK_CURRENT.THROUGH_EFFECT
     *
     * @mbggenerated
     */
    public Short getThroughEffect() {
        return throughEffect;
    }

    public boolean isVisit() {
        return isVisit;
    }

    public void setVisit(boolean visit) {
        isVisit = visit;
    }

    public boolean isNoised() {
        return isNoised;
    }

    public void setNoised(boolean noised) {
        isNoised = noised;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BLOCK_CURRENT.THROUGH_EFFECT
     *
     * @param throughEffect the value for T_BLOCK_CURRENT.THROUGH_EFFECT
     *
     * @mbggenerated
     */

    public void setThroughEffect(Short throughEffect) {
        this.throughEffect = throughEffect;
    }


    public String getDirectiontext() {
        return directiontext;
    }

    public void setDirectiontext(String directiontext) {
        this.directiontext = directiontext;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BLOCK_CURRENT.DIRECTION
     *
     * @mbggenerated
     */
    private String directiontext;

    public String getRoadRangText() {
        return roadRangText;
    }

    public void setRoadRangText(String roadRangText) {
        this.roadRangText = roadRangText;
    }

    private String roadRangText;

    private boolean isVisit = false;//是佛访问标记
    private boolean isNoised = false;//是否是噪音数据



    public Object clone() {
        T_BLOCK_YH_CURRENT o = null;
        o = new T_BLOCK_YH_CURRENT();
        o.setId(this.id);
        o.setRoadcode(this.roadcode);
        o.setRoadname(this.roadname);
        o.setRoadstart(this.roadstart);
        o.setRoadend(this.roadend);
        o.setDirection(this.direction);
        o.setDetectTime(this.detectTime);
        o.setDistcode(this.distcode);
        o.setCloseable(this.closeable);
        o.setSysOtime(this.sysOtime);
        o.setSource(this.source);
        o.setCenterPoint(this.centerPoint);
        return o;
    }
}