package com.jolin.entity;

import java.math.BigDecimal;

public class Student {

        private Integer id;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column User.name
         *
         * @mbggenerated
         */
        private String name;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column User.age
         *
         * @mbggenerated
         */
        private Integer age;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column User.emails
         *
         * @mbggenerated
         */
        private Integer[] emails;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column User.address
         *
         * @mbggenerated
         */
        private Object[] address;


        private BigDecimal[] coordinates;

        public BigDecimal[] getCoordinates() {
            return coordinates;
        }

        public void setCoordinates(BigDecimal[] coordinates) {
            this.coordinates = coordinates;
        }

    /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column User.id
         *
         * @return the value of User.id
         *
         * @mbggenerated
         */
        public Integer getId() {
            return id;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column User.id
         *
         * @param id the value for User.id
         *
         * @mbggenerated
         */
        public void setId(Integer id) {
            this.id = id;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column User.name
         *
         * @return the value of User.name
         *
         * @mbggenerated
         */
        public String getName() {
            return name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column User.name
         *
         * @param name the value for User.name
         *
         * @mbggenerated
         */
        public void setName(String name) {
            this.name = name == null ? null : name.trim();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column User.age
         *
         * @return the value of User.age
         *
         * @mbggenerated
         */
        public Integer getAge() {
            return age;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column User.age
         *
         * @param age the value for User.age
         *
         * @mbggenerated
         */
        public void setAge(Integer age) {
            this.age = age;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column User.emails
         *
         * @return the value of User.emails
         *
         * @mbggenerated
         */
        public Integer[] getEmails() {
            return emails;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column User.emails
         *
         * @param emails the value for User.emails
         *
         * @mbggenerated
         */
        public void setEmails(Integer[] emails) {
            this.emails = emails;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column User.address
         *
         * @return the value of User.address
         *
         * @mbggenerated
         */
        public Object[] getAddress() {
            return address;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column User.address
         *
         * @param address the value for User.address
         *
         * @mbggenerated
         */
        public void setAddress(Object[] address) {
            this.address = address;
        }
}
